PRAGMA defer_foreign_keys=ON;
PRAGMA legacy_alter_table=ON;
ALTER TABLE posts RENAME TO posts_prior;
CREATE TABLE posts(post_uid TEXT PRIMARY KEY,root_uid TEXT NOT NULL REFERENCES roots(root_uid) ON DELETE RESTRICT,post_no INTEGER NOT NULL CHECK(post_no>=0),legacy_seq INTEGER NOT NULL CHECK(legacy_seq>=0),state TEXT NOT NULL,board TEXT NOT NULL,filename TEXT,header_at TEXT,created_at TEXT NOT NULL,author_agent TEXT,content_sha256 TEXT,drive_file_id TEXT UNIQUE,drive_url TEXT,registration_state TEXT NOT NULL CHECK(registration_state IN ('reserved','published','drive_verified','abandoned','legacy','conflict')),reserved_until TEXT,source TEXT NOT NULL CHECK(source IN ('native','legacy_import')),CHECK(source='legacy_import' OR author_agent IS NOT NULL),UNIQUE(root_uid,post_no));
INSERT INTO posts SELECT * FROM posts_prior;
DROP TABLE posts_prior;
CREATE INDEX idx_posts_query ON posts(created_at,post_uid);
CREATE INDEX idx_posts_state ON posts(board,state,registration_state);
PRAGMA legacy_alter_table=OFF;
ALTER TABLE assignments RENAME TO assignments_prior;
CREATE TABLE assignments(post_uid TEXT NOT NULL REFERENCES posts(post_uid) ON DELETE RESTRICT,agent_id TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('responsible','requester','assignee','reviewer','observer')),active INTEGER NOT NULL CHECK(active IN (0,1)),PRIMARY KEY(post_uid,agent_id,role));
INSERT INTO assignments SELECT * FROM assignments_prior;
DROP TABLE assignments_prior;
CREATE INDEX idx_assignments_agent ON assignments(agent_id,active,role,post_uid);
ALTER TABLE artifacts RENAME TO artifacts_prior;
CREATE TABLE artifacts(drive_file_id TEXT PRIMARY KEY,parent_post_uid TEXT REFERENCES posts(post_uid) ON DELETE RESTRICT,kind TEXT NOT NULL CHECK(kind IN ('signature')),drive_url TEXT NOT NULL,filename TEXT NOT NULL,content_sha256 TEXT,verification_state TEXT NOT NULL CHECK(verification_state IN ('observed','verified','orphan','conflict')));
INSERT INTO artifacts SELECT * FROM artifacts_prior;
DROP TABLE artifacts_prior;
CREATE UNIQUE INDEX idx_artifact_parent_kind ON artifacts(parent_post_uid,kind);
ALTER TABLE verification_reports RENAME TO verification_reports_prior;
CREATE TABLE verification_reports(id INTEGER PRIMARY KEY AUTOINCREMENT,post_uid TEXT NOT NULL REFERENCES posts(post_uid) ON DELETE RESTRICT,verifier_principal TEXT NOT NULL,observed_json TEXT NOT NULL,valid INTEGER NOT NULL CHECK(valid IN (0,1)),evidence TEXT NOT NULL,created_at TEXT NOT NULL);
INSERT INTO verification_reports SELECT * FROM verification_reports_prior;
DROP TABLE verification_reports_prior;
CREATE INDEX idx_verification_post ON verification_reports(post_uid,created_at);
ALTER TABLE import_observations RENAME TO import_observations_prior;
CREATE TABLE import_observations(import_run_id TEXT NOT NULL REFERENCES import_runs(run_id) ON DELETE RESTRICT,drive_file_id TEXT NOT NULL,post_uid TEXT REFERENCES posts(post_uid) ON DELETE RESTRICT,metadata_hash TEXT NOT NULL CHECK(length(metadata_hash)=64),result TEXT NOT NULL CHECK(result IN ('imported','warning','unchanged','metadata-mismatch','artifact','orphan-artifact','conflict')),warnings_json TEXT NOT NULL,PRIMARY KEY(import_run_id,drive_file_id));
INSERT INTO import_observations SELECT * FROM import_observations_prior;
DROP TABLE import_observations_prior;
CREATE INDEX idx_import_observation_result ON import_observations(import_run_id,result);
DROP TRIGGER IF EXISTS native_publish_responsible;
CREATE TRIGGER native_publish_responsible BEFORE UPDATE OF registration_state ON posts WHEN NEW.source='native' AND NEW.registration_state IN ('published','drive_verified') AND NOT EXISTS(SELECT 1 FROM assignments WHERE post_uid=NEW.post_uid AND role='responsible' AND active=1) BEGIN SELECT RAISE(ABORT,'native publication requires responsible assignment'); END;
