#!/usr/bin/env python3
#
# TownSquare — Copyright (c) 2026 Yes.No.Maybe
# Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.
# Noncommercial use is free. Commercial use requires a separate licence.
#
"""Per-user install / disable / rollback for the read-only canary host reader.

VR-20261008-townsquare-183. No service framework: a version-pinned copy of the
`hostreader` package, a `current` symlink, one generated run.sh, and one tagged
cron line. Only that tagged line is ever added or removed; every other crontab
line is passed through byte-for-byte.

    cable-reader-deploy.py install --commit REV [--base-url URL] [--home DIR]
    cable-reader-deploy.py disable  [--home DIR]   # remove the cron line only
    cable-reader-deploy.py rollback [--home DIR]   # select previous release, or remove install
    cable-reader-deploy.py status   [--home DIR]
"""
from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
import sys
import tarfile
import io
from pathlib import Path

STORY_REF = "VR-20261008-townsquare-183"
MARKER = "# townsquare-canary-reader"
SCHEDULE = "* * * * *"
DEFAULT_BASE_URL = "http://192.168.2.3:18503"
RUN_SH = """#!/bin/sh
# Generated by cable-reader-deploy.py ({story}). Holds no credentials.
PY={py}
BASE={base}
INSTALL={install}
STATE_DIR={state}
LOG="$STATE_DIR/reader.log"
umask 077
mkdir -p "$STATE_DIR"
ts() {{ date -u +%Y-%m-%dT%H:%M:%SZ; }}
exec 9>"$STATE_DIR/run.lock"
if ! flock -n 9; then
  echo "$(ts) SKIPPED previous run still holds the lock" >>"$LOG"
  exit 0
fi
if [ -f "$LOG" ] && [ "$(wc -c <"$LOG")" -gt 262144 ]; then
  tail -n 1000 "$LOG" >"$LOG.tmp" && mv "$LOG.tmp" "$LOG"
fi
CUR="$INSTALL/current"
if [ ! -d "$CUR/hostreader" ]; then
  echo "$(ts) FAILED rc=3 no active release at $CUR" >>"$LOG"
  exit 3
fi
rev=$(cat "$CUR/REVISION" 2>/dev/null || echo unknown)
cd "$CUR" || exit 3
out=$(timeout 50 "$PY" -m hostreader --base-url "$BASE" \\
  --state-file "$STATE_DIR/state.json" --inbox-file "$STATE_DIR/INBOX.txt" 2>&1)
rc=$?
echo "$(ts) rc=$rc client=$rev $(printf %s "$out" | tr '\\n' ' ')" >>"$LOG"
exit $rc
"""


class DeployError(RuntimeError):
    pass


def paths(home):
    home = Path(home)
    install = home / ".local/share/townsquare-reader"
    return {"install": install, "releases": install / "releases", "current": install / "current",
            "previous": install / "previous", "run": install / "run.sh",
            "state": home / ".townsquare-reader"}


def cron_line(run_sh):
    return f"{SCHEDULE} {run_sh} {MARKER}"


def read_crontab():
    proc = subprocess.run(["crontab", "-l"], capture_output=True)
    if proc.returncode == 0:
        return proc.stdout
    if b"no crontab" in proc.stderr.lower():
        return b""
    raise DeployError(f"crontab -l failed: {proc.stderr.decode(errors='replace').strip()}")


def write_crontab(data):
    proc = subprocess.run(["crontab", "-"], input=data, capture_output=True)
    if proc.returncode != 0:
        raise DeployError(f"crontab write failed: {proc.stderr.decode(errors='replace').strip()}")


def _ours(line):
    return line.rstrip(b"\r\n").endswith(MARKER.encode())


def set_cron(line):
    """Add/replace our line (None removes it). Returns True if the crontab changed."""
    old = read_crontab()
    kept = [l for l in old.splitlines(keepends=True) if not _ours(l)]
    if kept and not kept[-1].endswith(b"\n"):
        kept[-1] += b"\n"
    new = b"".join(kept) + (line.encode() + b"\n" if line else b"")
    if new == old:
        return False
    write_crontab(new)
    if read_crontab() != new:
        raise DeployError("crontab did not read back as written")
    return True


def git(repo, *args):
    proc = subprocess.run(["git", "-C", str(repo), *args], capture_output=True)
    if proc.returncode != 0:
        raise DeployError(f"git {' '.join(args)} failed: {proc.stderr.decode(errors='replace').strip()}")
    return proc.stdout


def _link(target, link):
    tmp = link.with_name(link.name + ".new")
    tmp.unlink(missing_ok=True)
    tmp.symlink_to(target)
    os.replace(tmp, link)


def _release_name(p, link):
    return Path(os.readlink(link)).name if link.is_symlink() else None


def install(home, repo, commit, base_url):
    p = paths(home)
    full = git(repo, "rev-parse", "--verify", f"{commit}^{{commit}}").decode().strip()
    short = git(repo, "rev-parse", "--short=7", full).decode().strip()
    tree = git(repo, "rev-parse", f"{full}:hostreader").decode().strip()
    release = p["releases"] / short
    if release.exists():
        if (release / "TREE").read_text().strip() != tree:
            raise DeployError(f"{release} exists with different content; refusing to overwrite")
    else:
        p["releases"].mkdir(parents=True, exist_ok=True)
        stage = p["releases"] / f".{short}.stage"
        shutil.rmtree(stage, ignore_errors=True)
        stage.mkdir()
        archive = git(repo, "archive", "--format=tar", full, "hostreader")
        with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
            tar.extractall(stage, filter="data")
        (stage / "REVISION").write_text(full + "\n")
        (stage / "TREE").write_text(tree + "\n")
        os.rename(stage, release)
    old = _release_name(p, p["current"])
    if old != short:
        if old:
            _link(Path("releases") / old, p["previous"])
        _link(Path("releases") / short, p["current"])
    py = shutil.which("python3")
    if not py:
        raise DeployError("python3 not found")
    p["state"].mkdir(parents=True, exist_ok=True)
    os.chmod(p["state"], 0o700)
    p["run"].write_text(RUN_SH.format(story=STORY_REF, py=shlex.quote(py), base=shlex.quote(base_url),
                                      install=shlex.quote(str(p["install"])), state=shlex.quote(str(p["state"]))))
    os.chmod(p["run"], 0o700)
    changed = set_cron(cron_line(str(p["run"])))
    return f"installed {short} ({full}); cron {'updated' if changed else 'unchanged'}"


def disable(home):
    return "cron entry removed" if set_cron(None) else "no canary cron entry present"


def rollback(home):
    p = paths(home)
    cur = _release_name(p, p["current"])
    if cur is None:
        raise DeployError("no active release to roll back")
    prev = _release_name(p, p["previous"])
    if prev and (p["releases"] / prev).is_dir():
        _link(Path("releases") / prev, p["current"])
        p["previous"].unlink()
        msg = f"current -> {prev}"
    else:
        set_cron(None)
        p["current"].unlink()
        p["previous"].unlink(missing_ok=True)
        p["run"].unlink(missing_ok=True)
        msg = "no previous release; cron entry and active install removed"
    shutil.rmtree(p["releases"] / cur)
    return f"rolled back {cur}: {msg}"


def status(home):
    p = paths(home)
    ours = [l.decode().rstrip() for l in read_crontab().splitlines() if _ours(l)]
    return "\n".join([f"current:  {_release_name(p, p['current'])}",
                      f"previous: {_release_name(p, p['previous'])}",
                      f"cron:     {ours[0] if ours else 'absent'}"])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("action", choices=("install", "disable", "rollback", "status"))
    ap.add_argument("--commit", help="git revision to install (required for install)")
    ap.add_argument("--repo", default=str(Path(__file__).resolve().parent.parent))
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL)
    ap.add_argument("--home", default=str(Path.home()))
    args = ap.parse_args(argv)
    try:
        if args.action == "install":
            if not args.commit:
                raise DeployError("install requires --commit")
            print(install(args.home, args.repo, args.commit, args.base_url))
        elif args.action == "disable":
            print(disable(args.home))
        elif args.action == "rollback":
            print(rollback(args.home))
        else:
            print(status(args.home))
    except DeployError as exc:
        print(f"cable-reader-deploy: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
